### ISSUE TITLE
Environment variables in contract

### ISSUE THREAD

**Issue by goastler** [use-ink/cargo-contract#1171]
Feature request: environment variables pass through to contract.

In other languages, e.g. javascript, you can run a command like so:
```
MY_VAR=5 node index.js
```
and the `index.js` code would have access to the `MY_VAR` variable.

It would be really neat if cargo contract could do the same thing. We've found ourselves needing environment variable frequently lately. Something along the lines of:
```
#[ink::contract]
pub mod mycontract {

    const ENV_A: u32 = 0; // by default, it is set to 0

    #[derive(Default)]
    #[ink(storage)]
    pub struct MyContract {}

    /// Implementation of the contract
    impl MyContract {
        #[ink(constructor)]
        pub fn new() -> Self {
            Self {}
        }

        #[ink(message)]
        pub fn get_a(&self) -> u32 {
            ENV_A
        }
    }
}
```

Then I could run `ENV_A=5 cargo contract build` to set the `ENV_A` variable to something different per build. It would also be amazing if this could work without having to declare the `ENV_A` variable at the top of the contract, but I imagine that's rather difficult to achieve!

Above is a contrived example; this technique really shines when the environment constants are accounts such as the admin account for the contract.

If you could give some guidance on how this could be implemented I'd be happy to have a crack at it

**Comment by cmichi** [comment]
I'm closing this issue, as it is already possible with standard Rust:

`lib.rs`:
```rust
#[ink::contract]
pub mod mycontract {
    use konst::{primitive::parse_u32, unwrap_ctx};
    const ENV_A: u32 = unwrap_ctx!(parse_u32(core::env!("ENV_A")));

    #[derive(Default)]
    #[ink(storage)]
    pub struct MyContract {}

    impl MyContract {
        #[ink(constructor)]
        pub fn new() -> Self {
            Self {}
        }

        #[ink(message)]
        pub fn get_a(&self) -> u32 {
            ENV_A
        }
    }
}
```

`Cargo.toml`:
```toml
[dependencies]
ink = { version = "5.0.0", default-features = false }
konst = "0.3.9"
```
