### ISSUE TITLE
`Deserialize` for `Value`

### ISSUE THREAD

**Issue by kevin-valerio** [use-ink/cargo-contract#1757]
Hello,

I am using the `Value` enum in my project and would like to use `Deserialize`, however `Value` [doesn't derive it](https://github.com/use-ink/cargo-contract/blob/29af9eee480c37fd4e3cd4a2464c9821822dbc82/crates/transcode/src/scon/mod.rs#L49). Would that be possible to make it Deserializable ?

Thank you very much :)

**Comment by cmichi** [comment]
@kevin-valerio I was in the process of implementing `Deserialize`, but then noticed that we already have this function: https://github.com/use-ink/cargo-contract/blob/master/crates/transcode/src/scon/parse.rs#L58-L63. It's just not publicly available on the crate yet. 

Would exposing this function already solve your need?

**Comment by kevin-valerio** [comment]
> @kevin-valerio I was in the process of implementing `Deserialize`, but then noticed that we already have this function: https://github.com/use-ink/cargo-contract/blob/master/crates/transcode/src/scon/parse.rs#L58-L63. It's just not publicly available on the crate yet.
> 
> Would exposing this function already solve your need?

Hey @cmichi , thanks for your reply! I already solved my problem since then
